name: Deploy_CDK
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  NODE_VERSION: 20.11.1
  PYTHON_VERSION: 3.12.2

jobs:
  deploy_cdk:
    name: CDK_DEPLOY
    environment: Dev
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install CDK
        run: |
          python -m pip install --upgrade pip
          npm install -g aws-cdk

      - name: Install Dependencies
        run: |
          npm ci
          cdk --version

      - name: Infrastructure Changes
        run: |
         cdk diff
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
         
      - name: Deploy AWS CDK Stack
        run: |
          cdk deploy --require-approval never
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            
      - name: Run Unit Tests
        run: |
          npm run test