name: Build_Lambdas
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.12.2

jobs:
  build_lambdas:
    name: CodeBuild-Lambda
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache poetry packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/cache
            ~/.cache/pypoetry/artifacts
          key: poetry-packages-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Setup Python tools
        run: |
          pip install poetry==1.7.1

      - name: Build and test all projects
        run: |
          chmod +x ci/scripts/code/build-all-poetry-projects.sh
          chmod +x ci/scripts/code/build-poetry-project.sh
          ci/scripts/code/build-all-poetry-projects.sh

      - name: Create test report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() && (!contains(github.ref, '/dependabot/'))
        with:
          check_name: Python_Tests
          files: |
            reports/*-junit.xml
